repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v4.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict

  - repo: https://github.com/psf/black.git
    rev: 23.9.1
    hooks:
      - id: black

  # run pytest locally, no git fetch needed
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: pytest -q
        language: system
        pass_filenames: false
